modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/teamauroura/horizons/issues"
license = "All Rights Reserved"

[[mods]]
    modId = "horizons"
    version = "1.0.0"
    displayName = "Horizons"
    logoFile = "logo.png"
    itemIcon = "horizons:gooseberries"
    configBackground = "horizons:textures/block/cypress_log.png"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/horizons"
    authors = "Team Aurora"
    credits = "rose_"
    description = '''A mod about adding biomes with realism and the core Minecraft experience in mind.'''

[[dependencies.horizons]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.horizons]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.horizons]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.1.1,)"
    ordering = "BEFORE"
    side = "BOTH"
